services:
  web:
    build: ./web
    ports:
      - 5173:5173
    command: npm run dev
    networks:
      - api
    container_name: cadquery2web_web
  node:
    build: ./node
    ports:
      - 49158:3000
    env_file:
      - ./node/.env
    depends_on:
      - cadquery
    volumes:
      - ./logs:/logs
    networks:
      - cadquery
      - api
    container_name: cadquery2web_node
  cadquery:
    build: ./cadquery
    ports:
      - 49159:5000
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
      - /home/cadquery/.cache/ezdxf:rw,noexec,nosuid,uid=1000,gid=1000
    user: cadquery
    mem_limit: 512m
    memswap_limit: 512m
    ulimits:
      nproc: 100
      nofile:
        soft: 1000
        hard: 1000
    networks:
      - cadquery
    container_name: cadquery2web_cadquery
networks:
  cadquery:
    driver: bridge
  api:
    driver: bridge
